const state={products:[...PRODUCTS],cart:JSON.parse(localStorage.getItem('printlab_cart')||'[]'),favorites:JSON.parse(localStorage.getItem('printlab_favorites')||'[]'),orders:JSON.parse(localStorage.getItem('printlab_orders')||'[]'),coupon:null,shipping:0};
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(v);
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
function save(){localStorage.setItem('printlab_cart',JSON.stringify(state.cart));localStorage.setItem('printlab_favorites',JSON.stringify(state.favorites));localStorage.setItem('printlab_orders',JSON.stringify(state.orders));}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),2400)}
function productCard(p){const fav=state.favorites.includes(p.id);return `<article class="product-card reveal"><div class="product-image"><div class="mock-product" style="--pc:${p.color}"></div>${p.sale?'<span class="badge">OFERTA</span>':''}<button class="heart" data-fav="${p.id}" aria-label="Favoritar">${fav?'♥':'♡'}</button></div><div class="product-info"><div class="product-meta"><h3>${p.name}</h3><span class="rating">★ ${p.rating.toFixed(1)}</span></div><p>${p.description}</p><div class="price-row"><div><strong class="price">${money(p.price)}</strong>${p.oldPrice?`<span class="old-price">${money(p.oldPrice)}</span>`:''}</div><button class="add-btn" data-add="${p.id}">Adicionar</button></div></div></article>`}
function renderProducts(){const query=$('#searchInput').value.trim().toLowerCase(),cat=$('#categoryFilter').value,mat=$('#materialFilter').value,max=Number($('#priceFilter').value),sale=$('#saleFilter').checked,sort=$('#sortSelect').value;let ps=state.products.filter(p=>(!query||`${p.name} ${p.description}`.toLowerCase().includes(query))&&(cat==='all'||p.category===cat)&&(mat==='all'||p.material===mat)&&p.price<=max&&(!sale||p.sale));ps.sort((a,b)=>sort==='priceAsc'?a.price-b.price:sort==='priceDesc'?b.price-a.price:sort==='rating'?b.rating-a.rating:sort==='newest'?b.id-a.id:b.sold-a.sold);$('#resultCount').textContent=`${ps.length} produto${ps.length===1?'':'s'}`;$('#productGrid').innerHTML=ps.length?ps.map(productCard).join(''):`<div class="quote-placeholder" style="grid-column:1/-1">Nenhum produto encontrado.</div>`}
function cartCount(){return state.cart.reduce((s,i)=>s+i.qty,0)}
function shippingForCep(cep){const digits=String(cep).replace(/\D/g,'');if(digits.length<5)return 0;const n=Number(digits.slice(0,3));if(n>=100&&n<400)return 14.9;if(n>=400&&n<600)return 19.9;if(n>=600&&n<900)return 24.9;return 17.9}
function cartTotals(){const subtotal=state.cart.reduce((s,i)=>{const p=PRODUCTS.find(x=>x.id===i.id);return s+(p?p.price*i.qty:0)},0);const discount=state.coupon?.type==='percent'?subtotal*state.coupon.value:state.coupon?.type==='fixed'?Math.min(subtotal,state.coupon.value):0;return {subtotal,discount,shipping:state.shipping,total:Math.max(0,subtotal-discount+state.shipping)}}
function renderCart(){const count=cartCount();$('#cartCount').textContent=count;const el=$('#cartItems');if(!state.cart.length){el.innerHTML='<div class="empty-cart"><div><div style="font-size:38px">🛒</div><p>Seu carrinho está vazio.</p></div></div>'}else{el.innerHTML=state.cart.map(i=>{const p=PRODUCTS.find(x=>x.id===i.id);return p?`<div class="cart-item"><div class="cart-item-image" style="--ci:${p.color}"></div><div><h4>${p.name}</h4><p>${money(p.price)} • ${p.material}</p><div class="qty"><button data-minus="${p.id}">−</button><span>${i.qty}</span><button data-plus="${p.id}">+</button></div></div><button class="remove" data-remove="${p.id}">×</button></div>`:''}).join('')};const t=cartTotals();$('#cartSubtotal').textContent=money(t.subtotal);$('#cartDiscount').textContent=`- ${money(t.discount)}`;$('#cartShipping').textContent=t.shipping?money(t.shipping):'Calcular';$('#cartTotal').textContent=money(t.total);save()}
function addToCart(id,qty=1){const existing=state.cart.find(i=>i.id===id);if(existing)existing.qty+=qty;else state.cart.push({id,qty});renderCart();toast('Produto adicionado ao carrinho ✓');openDrawer()}
function openDrawer(){ $('#cartDrawer').classList.add('open');$('#overlay').classList.add('open');$('#cartDrawer').setAttribute('aria-hidden','false') }function closeDrawer(){$('#cartDrawer').classList.remove('open');$('#overlay').classList.remove('open');$('#cartDrawer').setAttribute('aria-hidden','true')}
function openModal(id){$(id).classList.add('open')}function closeModals(){$$('.modal').forEach(m=>m.classList.remove('open'));}
function showProduct(id){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;$('#productModalContent').innerHTML=`<div class="product-modal-content"><div class="modal-product-image"><div class="mock-product" style="--pc:${p.color}"></div></div><div class="product-detail"><p class="eyebrow">${p.category.toUpperCase()} • ${p.material}</p><h2>${p.name}</h2><p class="desc">${p.description}</p><div class="detail-grid">${Object.entries(p.details).map(([k,v])=>`<div><small>${k}</small><strong>${v}</strong></div>`).join('')}</div><div class="price-row"><strong class="price">${money(p.price)}</strong><span class="rating">★ ${p.rating.toFixed(1)} • ${p.sold} vendidos</span></div><div style="margin-top:20px"><button class="btn btn-primary full" data-add="${p.id}">Adicionar ao carrinho</button></div></div></div>`;openModal('#productModal')}
function applyCoupon(){const code=$('#couponInput').value.trim().toUpperCase();const map={PRIMEIRA10:{type:'percent',value:.10},PRINT15:{type:'fixed',value:15},FRETE0:{type:'fixed',value:0,freeShipping:true}};if(!map[code]){toast('Cupom inválido');return}state.coupon={...map[code],code};if(state.coupon.freeShipping)state.shipping=0;toast(`Cupom ${code} aplicado ✓`);renderCart()}
function updateCustom(){const text=$('#customText').value||'SEU TEXTO';$('#previewText').textContent=text.toUpperCase();const colorMap={preto:'#171a24',branco:'#e5e7eb',roxo:'#8b5cf6',azul:'#2563eb',vermelho:'#ef4444'};$('#customPreview').style.background=`linear-gradient(145deg,${colorMap[$('#customColor').value]},#0a0e18)`;let price=39.9+({'P':0,'M':10,'G':22}[$('#customSize').value]||0)+({'PLA':0,'PETG':8,'Resina':19}[$('#customMaterial').value]||0);$('#customPrice').textContent=money(price);return price}
function quoteEstimate(){const file=$('#modelFile').files[0];const qty=Math.max(1,Number($('#quoteQty').value)||1),material=$('#quoteMaterial').value,quality=$('#quoteQuality').value;if(!file){toast('Selecione um arquivo 3D primeiro');return}const size=Math.min(file.size/1024/1024,50);const weight=Math.max(30,Math.round(42+size*55));const materialRate={PLA:.085,PETG:.11,ABS:.105,Resina:.22}[material];const qMult={standard:1,fine:1.2,ultra:1.46}[quality];const materialCost=weight*materialRate;const printTime=(weight/23)*qMult;const labor=11+printTime*1.5;const energy=printTime*.65;const subtotal=(materialCost+labor+energy+5)*qty;const total=subtotal<59.9?subtotal+6.5:subtotal;$('#quoteResult').innerHTML=`<p class="eyebrow">SIMULAÇÃO</p><h3>Estimativa do seu projeto</h3><div class="quote-breakdown"><div><span>Arquivo</span><strong>${file.name}</strong></div><div><span>Peso estimado / un.</span><strong>${weight} g</strong></div><div><span>Tempo estimado / un.</span><strong>${printTime.toFixed(1)} h</strong></div><div><span>Material</span><strong>${material}</strong></div><div><span>Quantidade</span><strong>${qty}</strong></div><div><span>Produção + energia</span><strong>${money(labor+energy+materialCost)}</strong></div><div class="quote-total"><span>Total estimado</span><strong>${money(total)}</strong></div></div><p style="color:#748097;font-size:11px;margin-top:18px">Essa é uma estimativa automática. O preço final pode mudar após a análise geométrica do arquivo.</p><button class="btn btn-primary full" id="quoteAddBtn" style="margin-top:12px">Salvar orçamento</button>`;$('#quoteAddBtn').onclick=()=>{localStorage.setItem('printlab_last_quote',JSON.stringify({file:file.name,material,quality,qty,total}));toast('Orçamento salvo nesta sessão ✓')};}
function checkoutSummary(){const t=cartTotals(),pix=$('#paymentMethod').value==='pix'?t.total*.95:t.total;$('#checkoutSummary').innerHTML=`<div><span>Subtotal</span><strong>${money(t.subtotal)}</strong></div><div><span>Desconto</span><strong>- ${money(t.discount)}</strong></div><div><span>Frete</span><strong>${money(t.shipping)}</strong></div><div class="grand"><span>Total</span><strong>${money(pix)}</strong></div><small style="color:#738097">${$('#paymentMethod').value==='pix'?'Desconto de 5% aplicado ao PIX.':''}</small>`}
function accountRender(){$('#accountOrders').textContent=state.orders.length;$('#accountFavorites').textContent=state.favorites.length;$('#accountPoints').textContent=state.orders.reduce((s,o)=>s+Math.floor(o.total),0);$('#accountOrdersList').innerHTML=state.orders.length?state.orders.slice().reverse().map(o=>`<div class="order-row"><strong>#${o.id}</strong><span>${o.date} • ${money(o.total)}</span><span>${o.status}</span></div>`).join(''):'<p style="color:#68738a">Você ainda não tem pedidos.</p>'}
function bind(){
  $('#productGrid').addEventListener('click',e=>{const add=e.target.closest('[data-add]'),fav=e.target.closest('[data-fav]');if(add){addToCart(Number(add.dataset.add));return}if(fav){const id=Number(fav.dataset.fav);state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];save();renderProducts();toast(state.favorites.includes(id)?'Adicionado aos favoritos ♥':'Removido dos favoritos')}});
  $('#productGrid').addEventListener('dblclick',e=>{const card=e.target.closest('.product-card');if(!card)return;const buttons=card.querySelector('[data-add]');showProduct(Number(buttons.dataset.add))});
  $('#cartItems').addEventListener('click',e=>{const id=Number((e.target.closest('[data-plus]')||e.target.closest('[data-minus]')||e.target.closest('[data-remove]'))?.dataset.plus||e.target.closest('[data-minus]')?.dataset.minus||e.target.closest('[data-remove]')?.dataset.remove);if(!id)return;const item=state.cart.find(i=>i.id===id);if(e.target.closest('[data-plus]'))item.qty++;if(e.target.closest('[data-minus]')){item.qty--;if(item.qty<=0)state.cart=state.cart.filter(i=>i.id!==id)}if(e.target.closest('[data-remove]'))state.cart=state.cart.filter(i=>i.id!==id);renderCart()});
  ['searchInput','categoryFilter','materialFilter','priceFilter','saleFilter','sortSelect'].forEach(id=>$('#'+id).addEventListener(id==='priceFilter'?'input':'change',()=>{if(id==='priceFilter')$('#priceValue').textContent=`Até ${money(Number($('#priceFilter').value))}`;renderProducts()}));$('#applyFilters').onclick=()=>renderProducts();$('#clearFilters').onclick=()=>{$('#searchInput').value='';$('#categoryFilter').value='all';$('#materialFilter').value='all';$('#priceFilter').value=300;$('#saleFilter').checked=false;renderProducts()};
  $('#cartBtn').onclick=openDrawer;$('#closeCart').onclick=closeDrawer;$('#overlay').onclick=closeDrawer;$('#couponBtn').onclick=applyCoupon;$('#shippingCep').addEventListener('input',e=>{const digits=e.target.value.replace(/\D/g,'').slice(0,8);e.target.value=digits.length>5?digits.slice(0,5)+'-'+digits.slice(5):digits;state.shipping=state.coupon?.freeShipping?0:shippingForCep(digits);renderCart()});$('#checkoutBtn').onclick=()=>{if(!state.cart.length){toast('Adicione algum produto primeiro');return}checkoutSummary();openModal('#checkoutModal')};$('#paymentMethod').onchange=checkoutSummary;
  $('#closeCheckout').onclick=closeModals;$('#closeProductModal').onclick=closeModals;$('#closeAccount').onclick=closeModals;
  $('#accountBtn').onclick=()=>{accountRender();openModal('#accountModal')};
  $('#mobileMenuBtn').onclick=()=>$('#mainNav').classList.toggle('open');$$('#mainNav a').forEach(a=>a.onclick=()=>$('#mainNav').classList.remove('open'));$('#searchBtn').onclick=()=>{document.querySelector('#catalogo').scrollIntoView({behavior:'smooth'});setTimeout(()=>$('#searchInput').focus(),350)};$('#mobileFilterBtn').onclick=()=>$('.filters').classList.toggle('open');$('#closeFilters').onclick=()=>$('.filters').classList.remove('open');
  ['customText','customColor','customMaterial','customSize'].forEach(id=>$('#'+id).addEventListener('input',updateCustom));$('#addCustomBtn').onclick=()=>{const p={id:100,name:`Personalizado — ${($('#customText').value||'Seu texto').slice(0,20)}`,material:$('#customMaterial').value,price:updateCustom(),color:'#8b5cf6',description:'Item personalizado configurado no site.'};PRODUCTS.push(p);state.cart.push({id:p.id,qty:1});renderCart();toast('Personalizado adicionado ✓');openDrawer()};
  $('#chooseFile').onclick=()=>$('#modelFile').click();$('#dropzone').onclick=e=>{if(!e.target.closest('button'))$('#modelFile').click()};$('#modelFile').onchange=()=>{const f=$('#modelFile').files[0];if(f){$('#fileName').textContent=`Arquivo selecionado: ${f.name}`;toast('Arquivo carregado ✓')}};$('#quoteForm').onsubmit=e=>{e.preventDefault();quoteEstimate()};
  $('#checkoutForm').onsubmit=e=>{e.preventDefault();const t=cartTotals(),method=$('#paymentMethod').value,total=method==='pix'?t.total*.95:t.total;const order={id:'PL'+Date.now().toString().slice(-6),date:new Date().toLocaleDateString('pt-BR'),total,status:'Pagamento pendente',method};state.orders.push(order);state.cart=[];save();renderCart();closeModals();closeDrawer();accountRender();toast(`Pedido #${order.id} criado ✓`)};
  document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add&&!e.target.closest('#productGrid')){addToCart(Number(add.dataset.add));return}if(e.target.closest('.product-card')&&!e.target.closest('button')){const id=Number(e.target.closest('.product-card').querySelector('[data-add]').dataset.add);showProduct(id)}});
}
function init(){renderProducts();renderCart();updateCustom();bind();new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.style.animationPlayState='running'}),{threshold:.08}).observe(document.querySelector('.hero-content'));}
init();
