const PRODUCTS = [
  {id:1,name:'Dragão Articulado',category:'Geek',material:'PLA',price:89.90,oldPrice:119.90,sale:true,rating:4.9,stock:7,sold:184,color:'#7c3aed',description:'Dragão articulado com segmentos móveis, pensado para coleção e presente.',details:{Peso:'184 g',Dimensões:'22 × 10 × 16 cm',Produção:'8–10 h',Acabamento:'Natural'}},
  {id:2,name:'Suporte Headset Nebula',category:'Suportes',material:'PETG',price:74.90,oldPrice:0,sale:false,rating:4.8,stock:12,sold:98,color:'#22d3ee',description:'Suporte robusto para headset, com base antiderrapante e visual futurista.',details:{Peso:'210 g',Dimensões:'14 × 14 × 25 cm',Produção:'6–8 h',Acabamento:'Natural'}},
  {id:3,name:'Vaso Geométrico',category:'Decoração',material:'PLA',price:49.90,oldPrice:69.90,sale:true,rating:4.7,stock:22,sold:151,color:'#db2777',description:'Vaso decorativo com padrão geométrico e parede otimizada para baixo peso.',details:{Peso:'122 g',Dimensões:'12 × 12 × 16 cm',Produção:'4–5 h',Acabamento:'Natural'}},
  {id:4,name:'Organizador Modular',category:'Utilidades',material:'PETG',price:39.90,oldPrice:0,sale:false,rating:4.6,stock:31,sold:81,color:'#e5e7eb',description:'Módulo empilhável para mesa, gaveta e bancada. Expanda conforme sua necessidade.',details:{Peso:'98 g',Dimensões:'18 × 9 × 5 cm',Produção:'3–4 h',Acabamento:'Natural'}},
  {id:5,name:'Chaveiro Personalizado',category:'Presentes',material:'PLA',price:24.90,oldPrice:34.90,sale:true,rating:4.9,stock:50,sold:302,color:'#f97316',description:'Chaveiro com nome ou palavra curta. Uma lembrança barata e feita para você.',details:{Peso:'24 g',Dimensões:'6 × 3 × 0,6 cm',Produção:'1–2 h',Acabamento:'Natural'}},
  {id:6,name:'Mini Figure Cyber Samurai',category:'Geek',material:'Resina',price:129.90,oldPrice:0,sale:false,rating:5.0,stock:4,sold:64,color:'#ef4444',description:'Miniatura de alta definição em resina, pronta para pintura ou exposição.',details:{Peso:'92 g',Dimensões:'11 × 8 × 15 cm',Produção:'10–14 h',Acabamento:'Resina'}},
  {id:7,name:'Base para Controle',category:'Suportes',material:'ABS',price:59.90,oldPrice:79.90,sale:true,rating:4.8,stock:16,sold:115,color:'#facc15',description:'Base compacta para controle de videogame, com encaixe estável.',details:{Peso:'155 g',Dimensões:'16 × 11 × 7 cm',Produção:'5–6 h',Acabamento:'Natural'}},
  {id:8,name:'Planter Minimal',category:'Decoração',material:'PLA',price:44.90,oldPrice:0,sale:false,rating:4.5,stock:18,sold:43,color:'#84cc16',description:'Vaso minimalista para plantas pequenas, com visual limpo e moderno.',details:{Peso:'116 g',Dimensões:'11 × 11 × 12 cm',Produção:'4 h',Acabamento:'Natural'}},
  {id:9,name:'Cubo Fidget Mecânico',category:'Presentes',material:'PLA',price:29.90,oldPrice:39.90,sale:true,rating:4.8,stock:26,sold:127,color:'#2563eb',description:'Objeto de mesa articulado para explorar mecanismos e aliviar a inquietação.',details:{Peso:'62 g',Dimensões:'6 × 6 × 6 cm',Produção:'2–3 h',Acabamento:'Natural'}}
];
